In [1]:
import pandas as pd
url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv'
df = pd.read_csv(url)
url2='https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv'
df2=pd.read_csv(url2)
#covid_confirmed = pd.read_csv(COVID_CONFIRMED_URL)

In [2]:
is_US=df2['Country/Region']=='US'
df_US=df2[is_US]

In [3]:
is_NY =  df['Province_State']=='New York'
df_NY = df[is_NY]
is_Erie = df_NY['Admin2']=='Erie'
df_Erie = df_NY[is_Erie]
list(df_NY.columns)
df_NY = df_NY.drop(['UID','iso2','iso3','code3',
 'FIPS','Admin2','Country_Region', 'Province_State','Lat','Long_','Combined_Key','1/22/20','1/23/20','1/24/20','1/25/20','1/26/20','1/27/20',
 '1/28/20','1/29/20','1/30/20','1/31/20','2/1/20','2/2/20','2/3/20','2/4/20','2/5/20','2/6/20','2/7/20',
 '2/8/20','2/9/20','2/10/20','2/11/20','2/12/20','2/13/20','2/14/20','2/15/20','2/16/20','2/17/20','2/18/20',
 '2/19/20','2/20/20','2/21/20','2/22/20','2/23/20','2/24/20','2/25/20','2/26/20', '2/27/20','2/28/20','2/29/20'], axis=1)
df_NY_all=df_NY.agg([sum])

In [4]:
df_Erie = df_Erie.drop(['UID','iso2','iso3','code3',
 'FIPS','Admin2', 'Lat','Long_','Combined_Key','Province_State','1/22/20','1/23/20','1/24/20','1/25/20','1/26/20','1/27/20',
 '1/28/20','1/29/20','1/30/20','1/31/20','2/1/20','2/2/20','2/3/20','2/4/20','2/5/20','2/6/20','2/7/20',
 '2/8/20','2/9/20','2/10/20','2/11/20','2/12/20','2/13/20','2/14/20','2/15/20','2/16/20','2/17/20','2/18/20',
 '2/19/20','2/20/20','2/21/20','2/22/20','2/23/20','2/24/20','2/25/20','2/26/20', '2/27/20','2/28/20','2/29/20'], axis=1)

In [5]:
list(df_US.columns)
df_US = df_US.drop(['Province/State','Lat','Country/Region',
 'Long','1/22/20','1/23/20', '1/24/20','1/25/20','1/26/20','1/27/20','1/28/20', '1/29/20','1/30/20','1/31/20',
 '2/1/20','2/2/20','2/3/20','2/4/20','2/5/20','2/6/20','2/7/20','2/8/20', '2/9/20','2/10/20','2/11/20','2/12/20','2/13/20','2/14/20',
 '2/15/20','2/16/20', '2/17/20', '2/18/20', '2/19/20', '2/20/20', '2/21/20', '2/22/20', '2/23/20', '2/24/20', 
'2/25/20', '2/26/20', '2/27/20','2/28/20','2/29/20'],axis=1)

In [6]:
df_US['Region']='US'
df_Erie['Region']='Erie'
df_NY_all['Region']="NY"

In [9]:
df_US2=pd.melt(df_US, id_vars=['Region'],value_vars=['3/1/20','3/2/20','3/3/20','3/4/20','3/5/20','3/6/20','3/7/20','3/8/20','3/9/20','3/10/20','3/11/20','3/12/20',
 '3/13/20','3/14/20','3/15/20','3/16/20','3/17/20','3/18/20','3/19/20','3/20/20','3/21/20','3/22/20',
 '3/23/20','3/24/20','3/25/20','3/26/20','3/27/20','3/28/20', '3/29/20', '3/30/20','3/31/20','4/1/20',
 '4/2/20','4/3/20','4/4/20','4/5/20','4/6/20','4/7/20','4/8/20', '4/9/20','4/10/20', '4/11/20','4/12/20'],
                        var_name='Day',value_name='US')

df_NY2=pd.melt(df_NY_all, id_vars=['Region'],value_vars=['3/1/20','3/2/20','3/3/20','3/4/20','3/5/20','3/6/20','3/7/20','3/8/20','3/9/20','3/10/20','3/11/20','3/12/20',
 '3/13/20','3/14/20','3/15/20','3/16/20','3/17/20','3/18/20','3/19/20','3/20/20','3/21/20','3/22/20',
 '3/23/20','3/24/20','3/25/20','3/26/20','3/27/20','3/28/20', '3/29/20', '3/30/20','3/31/20','4/1/20',
 '4/2/20','4/3/20','4/4/20','4/5/20','4/6/20','4/7/20','4/8/20', '4/9/20','4/10/20', '4/11/20','4/12/20'],
                        var_name='Day',value_name='NY')

df_Erie2=pd.melt(df_Erie, id_vars=['Region'],value_vars=['3/1/20','3/2/20','3/3/20','3/4/20','3/5/20','3/6/20','3/7/20','3/8/20','3/9/20','3/10/20','3/11/20','3/12/20',
 '3/13/20','3/14/20','3/15/20','3/16/20','3/17/20','3/18/20','3/19/20','3/20/20','3/21/20','3/22/20',
 '3/23/20','3/24/20','3/25/20','3/26/20','3/27/20','3/28/20', '3/29/20', '3/30/20','3/31/20','4/1/20',
 '4/2/20','4/3/20','4/4/20','4/5/20','4/6/20','4/7/20','4/8/20', '4/9/20','4/10/20', '4/11/20','4/12/20'],
                        var_name='Day',value_name='Erie')

df_US2=df_US2.drop(['Region'], axis=1)
df_NY2=df_NY2.drop(['Region'], axis=1)
df_Erie2=df_Erie2.drop(['Region'], axis=1)

result = pd.concat([df_US2, df_NY2, df_Erie2], axis=1, sort=False)
#cols = [2,4]
#result.drop(result.columns[cols],axis=1,inplace=True)

In [10]:
result

        Day      US      Day      NY      Day  Erie
0    3/1/20      74   3/1/20       0   3/1/20     0
1    3/2/20      98   3/2/20       1   3/2/20     0
2    3/3/20     118   3/3/20       2   3/3/20     0
3    3/4/20     149   3/4/20      11   3/4/20     0
4    3/5/20     217   3/5/20      23   3/5/20     0
5    3/6/20     262   3/6/20      31   3/6/20     0
6    3/7/20     402   3/7/20      76   3/7/20     0
7    3/8/20     518   3/8/20     106   3/8/20     0
8    3/9/20     583   3/9/20     142   3/9/20     0
9   3/10/20     959  3/10/20     150  3/10/20     0
10  3/11/20    1281  3/11/20     220  3/11/20     0
11  3/12/20    1663  3/12/20     327  3/12/20     0
12  3/13/20    2179  3/13/20     421  3/13/20     0
13  3/14/20    2727  3/14/20     613  3/14/20     3
14  3/15/20    3499  3/15/20     615  3/15/20     3
15  3/16/20    4632  3/16/20     967  3/16/20     7
16  3/17/20    6421  3/17/20    1578  3/17/20    11
17  3/18/20    7783  3/18/20    3038  3/18/20    20
18  3/19/20   13747  3/19/20    5704  3/19/20    28
19  3/20/20   19273  3/20/20    8403  3/20/20    47
20  3/21/20   25600  3/21/20   11727  3/21/20    50
21  3/22/20   33276  3/22/20   15800  3/22/20    56
22  3/23/20   43847  3/23/20   20884  3/23/20    87
23  3/24/20   53740  3/24/20   25681  3/24/20   114
24  3/25/20   65778  3/25/20   30841  3/25/20   122
25  3/26/20   83836  3/26/20   37877  3/26/20   206
26  3/27/20  101657  3/27/20   44876  3/27/20   245
27  3/28/20  121465  3/28/20   52410  3/28/20   318
28  3/29/20  140909  3/29/20   59648  3/29/20   414
29  3/30/20  161831  3/30/20   66663  3/30/20   443
30  3/31/20  188172  3/31/20   75833  3/31/20   499
31   4/1/20  213372   4/1/20   83948   4/1/20   582
32   4/2/20  243762   4/2/20   92506   4/2/20   617
33   4/3/20  275586   4/3/20  102987   4/3/20   734
34   4/4/20  308853   4/4/20  113833   4/4/20   808
35   4/5/20  337072   4/5/20  123160   4/5/20  1059
36   4/6/20  366667   4/6/20  131815   4/6/20  1148
37   4/7/20  396223   4/7/20  139875   4/7/20  1234
38   4/8/20  429052   4/8/20  151061   4/8/20  1335
39   4/9/20  461437   4/9/20  161779   4/9/20  1432
40  4/10/20  496535  4/10/20  172348  4/10/20  1498
41  4/11/20  526396  4/11/20  181026  4/11/20  1506
42  4/12/20  555313  4/12/20  189033  4/12/20  1571

In [ ]:
A=pd.merge(df_US, df_Erie, how='outer')

In [ ]:
A=pd.merge(A, df_NY_all, how='outer')

In [ ]:
A=A.drop(['Country_Region'],axis=1)

In [ ]:
 melted_df = pd.melt(A,id_vars=['Region'],
                        value_vars=['3/1/20','3/2/20','3/3/20','3/4/20','3/5/20','3/6/20','3/7/20','3/8/20','3/9/20','3/10/20','3/11/20','3/12/20',
 '3/13/20','3/14/20','3/15/20','3/16/20','3/17/20','3/18/20','3/19/20','3/20/20','3/21/20','3/22/20',
 '3/23/20','3/24/20','3/25/20','3/26/20','3/27/20','3/28/20', '3/29/20', '3/30/20','3/31/20','4/1/20',
 '4/2/20','4/3/20','4/4/20','4/5/20','4/6/20','4/7/20','4/8/20', '4/9/20','4/10/20', '4/11/20','4/12/20'],
                        var_name='Day',value_name='Cases')

In [14]:
result.iloc[:,0]

0      3/1/20
1      3/2/20
2      3/3/20
3      3/4/20
4      3/5/20
5      3/6/20
6      3/7/20
7      3/8/20
8      3/9/20
9     3/10/20
10    3/11/20
11    3/12/20
12    3/13/20
13    3/14/20
14    3/15/20
15    3/16/20
16    3/17/20
17    3/18/20
18    3/19/20
19    3/20/20
20    3/21/20
21    3/22/20
22    3/23/20
23    3/24/20
24    3/25/20
25    3/26/20
26    3/27/20
27    3/28/20
28    3/29/20
29    3/30/20
30    3/31/20
31     4/1/20
32     4/2/20
33     4/3/20
34     4/4/20
35     4/5/20
36     4/6/20
37     4/7/20
38     4/8/20
39     4/9/20
40    4/10/20
41    4/11/20
42    4/12/20
Name: Day, dtype: object